import { v4 as uuidv4 } from "uuid";

const recents = [
  {
    id: uuidv4(),
    contactId: "Amilia Elie",
    name: "Amilia Elie",
    type: "received",
    time: "Today 9:45AM",
    number: "+880 33456 777",
  },
  {
    id: uuidv4(),
    contactId: "Sergio Ramos",
    name: "Sergio Ramos",
    type: "outgoing",
    time: "Today 9:45AM",
    number: "+880 33456 777",
  },
  {
    id: uuidv4(),
    contactId: "Allison Becker",
    name: "Allison Becker",
    type: "received",
    time: "Today 9:45AM",
    number: "+880 33456 777",
  },
  {
    id: uuidv4(),
    contactId: "Kylian Mbappe",
    name: "Kylian Mbappe",
    type: "missed",
    time: "Today 9:45AM",
    number: "+880 33456 777",
  },
  {
    id: uuidv4(),
    contactId: "Allison Becker",
    name: "Allison Beaker",
    type: "outgoing",
    time: "Today 9:45AM",
    number: "+880 33456 777",
  },
  {
    id: uuidv4(),
    contactId: "Trent Arnold",
    name: "Trent Arnold",
    type: "outgoing",
    time: "Today 9:45AM",
    number: "+880 33456 777",
  },
  {
    id: uuidv4(),
    contactId: "Sergio Ramos",
    name: "Sergio Ramos",
    type: "received",
    time: "Today 9:45AM",
    number: "+880 33456 777",
  },
  {
    id: uuidv4(),
    contactId: "Cristiano Ronaldo",
    name: "Cristiano Ronaldo",
    type: "missed",
    time: "Today 9:45AM",
    number: "+880 33456 777",
  },
  {
    id: uuidv4(),
    contactId: "Allison Becker",
    name: "Allison Becker",
    type: "outgoing",
    time: "Today 9:45AM",
    number: "+880 33456 777",
  },
  {
    id: uuidv4(),
    contactId: "Cristiano Ronaldo",
    name: "Cristiano Ronaldo",
    type: "missed",
    time: "Today 9:45AM",
    number: "+880 33456 777",
  },
  {
    id: uuidv4(),
    contactId: "Allison Becker",
    name: "Allison Becker",
    type: "outgoing",
    time: "Today 9:45AM",
    number: "+880 33456 777",
  },
];

export default recents;
